// vue-pro/src/components/BtnTest.vue
<template>
  <div class="hello">
    <p>点击次数：{{ count }}</p>
    <p>
      <span>default样式：</span>
      <AiButton @aiClick="onClick"> Default Btn </AiButton>
      <AiButton @aiClick="onClick" :disabled="true"> Default Btn </AiButton>
      <span>default危险：</span>
      <AiButton @aiClick="onClick" :danger="true"> Default Btn </AiButton>
      <AiButton @aiClick="onClick" :disabled="true" :danger="true">
        Default Btn
      </AiButton>
    </p>
    <p>
      <span>primary样式：</span>
      <AiButton @aiClick="onClick" :type="'primary'"> Primary Btn </AiButton>
      <AiButton @aiClick="onClick" :disabled="true" :type="'primary'">
        Primary Btn
      </AiButton>
      <span>primary危险：</span>
      <AiButton @aiClick="onClick" :danger="true" :type="'primary'">
        Primary Btn
      </AiButton>
      <AiButton
        @aiClick="onClick"
        :disabled="true"
        :danger="true"
        :type="'primary'"
      >
        Primary Btn
      </AiButton>
    </p>
    <p>
      <span>dashed样式：</span>
      <AiButton @aiClick="onClick" :type="'dashed'"> Dashed Btn </AiButton>
      <AiButton @aiClick="onClick" :disabled="true" :type="'dashed'">
        Dashed Btn
      </AiButton>
      <span>dashed危险：</span>
      <AiButton @aiClick="onClick" :danger="true" :type="'dashed'">
        Dashed Btn
      </AiButton>
      <AiButton
        @aiClick="onClick"
        :disabled="true"
        :danger="true"
        :type="'dashed'"
      >
        Dashed Btn
      </AiButton>
    </p>
  </div>
</template>

<script>
import { AiButton } from "@ai.s/ui-components-vue";

export default {
  name: "BtnTest",
  components: {
    AiButton,
  },
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    onClick: function (event) {
      console.log(event);
      this.count += 1;
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
ai-button {
  margin: 0 10px;
}
</style>

// react-pro/src/BtnTest.js
import { useState } from 'react'
import { AiButton } from '@ai/ui-components-react'

function BtnTest() {
    const [count, setCount] = useState(0)

    const handleClick = (event) => {
        setCount(count + 1)
        console.log(event)
    }

    const renderData = () => {
        let data = []
        for (let i = 0; i < 500; i++) {
            const component = (
                <div key={`${i}-0`} className={"item"}>
                    <AiButton key={`${i}-1`} className={"btn-test"} >按钮1</AiButton>
                    <AiButton key={`${i}-2`} className={"btn-test"}>按钮2</AiButton>
                    <AiButton key={`${i}-3`} className={"btn-test"}>按钮3</AiButton>
                    <AiButton key={`${i}-4`} className={"btn-test"}>按钮4</AiButton>
                    <AiButton key={`${i}-5`} className={"btn-test"}>按钮5</AiButton>
                    {/* <button key={`${i}-1`} class={"btn-origin"}>按钮1</button>
					<button key={`${i}-2`} class={"btn-origin"}>按钮2</button>
					<button key={`${i}-3`} class={"btn-origin"}>按钮3</button>
					<button key={`${i}-4`} class={"btn-origin"}>按钮4</button>
					<button key={`${i}-5`} class={"btn-origin"}>按钮5</button> */}
                </div>
            )
            data = [...data, component]
        }

        return data
    }

    return (
        <div className="item">
            <div>
                <p>点击次数：{count}</p>
                <AiButton onAiClick={handleClick}>点击</AiButton>
                {renderData()}
            </div>
        </div>
    );
}

export default BtnTest;
