// vue3-pro/src/App.vue
<template>
  <div>
    <img alt="Vue logo" src="./assets/logo.png" />
    <HelloWorld />
    <hr />
    <BtnTest />
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";
import BtnTest from "./components/BtnTest.vue";

export default {
  name: "App",
  components: {
    HelloWorld,
    BtnTest,
  },
  data() {
    return {
      value: "aaa",
    };
  },
  methods: {
    onChange: function (event) {
      console.log(event);
    },
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

ai-button {
  margin: 0 10px;
}
</style>

// ng-pro/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ng-test';
  name = ''

  isConfirm = false

  onClick(event: any) {
    console.log(event)
    this.isConfirm = true
  }

  onAiInput(event: any) {
    console.log('input', event.target.value)
    this.name = event.target.value

    if (this.isConfirm) {
      this.isConfirm = false
    }
  }
}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  .spacer {
    flex: 1;
  }

  .toolbar {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 60px;
    display: flex;
    align-items: center;
    background-color: #1976d2;
    color: white;
    font-weight: 600;
  }

  .toolbar img {
    margin: 0 16px;
  }

  .content {
    position: absolute;
    top: 70px;
    right: 0;
    bottom: 0;
    left: 0;
    color: #000;
    text-align: center;
  }

  .ai-btn {
    margin-left: 20px;
  }

  .select-wrapper {
    margin-left: 42%;
    width: 200px;
    height: 30px;
  }

  .item {
    display: block;
    padding: 10px;
    margin-top: 20px;
    text-align: center;
  }

</style>

<!-- Toolbar -->
<div class="toolbar" role="banner">
  <img width="40" alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==" />
  <span>Welcome Angular</span>
  <div class="content">
    <div class="item">
      <ai-stringfy [data]="options"></ai-stringfy>
    </div>
    <div class="item">
      <h3>输入&按钮</h3>
      <span>姓名：</span>
      <ai-input (aiInput)="onAiInput($event)" placeholder="请输入..."></ai-input>
      <ai-button (aiClick)="onClick($event)" [disabled]="!name" class="ai-btn">确定</ai-button>
      <p *ngIf="isConfirm">Welcome! {{name}}</p>
    </div>
    <div class="item">
      <h3>下拉框选中项: {{selected.text}}</h3>
      <div class="select-wrapper">
        <ai-select 
        [selected]="selected" 
        (aiChange)="onSelectChange($event)" 
        [compareWith]="'id'"
        placeholder="请选择语言"
      >
          <ai-select-option *ngFor="let item of options" [option]="item">
            {{item.text}}
          </ai-select-option>
        </ai-select>
      </div>
    </div>
    <hr/>
    <btn-test></btn-test>
    <hr/>
    <input-test></input-test>
  </div>
</div>
